directory: /Volumes/Data/music
library: /Volumes/Data/music.blb
paths: 
  default: %asciify{%lower{$albumartist}}-%asciify{%lower{$album}}-$year/$track-%asciify{%lower{$title}}
  comp: varius-artists/$album%aunique{}/$track-%asciify{%lower{$title}}
import:
  move: no
original_date: yes
match:
  strong_rec_thresh: 0.1
  preferred:
    countries: [US, GB|UK]
    media: [CD, Digital Media|File]
    original_year: yes
replace:
  '\ ': _
plugins: ftintitle edit fetchart embedart scrub
fetchart:
  minwidth: 500
  maxwidth: 700
  enforceratio: yes
ftintitle:
  format: (feat. {0})

# replaygain:
#   backend: command
#   auto: no
#   overwrite: yes
# lastgenre:
#   canonical: yes
#   whitelist:
#     - acoustic music
#     - electronic
#     - hip hop
#     - classical
#     - rock
#     - jazz
