directory: /Volumes/DataHD/music
library: /Volumes/DataHD/zool-music.db
paths: 
  default: %asciify{%lower{$albumartist}}-%asciify{%lower{$album}}-$year/$track-%asciify{%lower{$title}}
  comp: various-artists/$album%aunique{}/$track-%asciify{%lower{$title}}
import:
  move: no
original_date: yes
match:
  strong_rec_thresh: 0.1
  preferred:
    countries: [US, GB|UK]
    media: [CD, Digital Media|File]
    original_year: yes
replace:
  '\ ': _
plugins: ftintitle edit fetchart embedart scrub export lastgenre
export:
  json:
    formatting:
      indent: 2
fetchart:
  minwidth: 500
  maxwidth: 700
  enforceratio: yes
ftintitle:
  format: (feat. {0})

# replaygain:
#   backend: command
#   auto: no
#   overwrite: yes
lastgenre:
  canonical: yes
  whitelist: ~/dotfiles/beets/.config/beets/genres-whitelist
